[package]
name = "rdr"
version = "0.1.0-beta.1"
edition = "2021"
authors = ["Bruce Flynn <brucef@ssec.wisc.edu>"]
repository = "https://gitlab.ssec.wisc.edu/brucef/rdr"
license-file = "LICENCE.txt"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
chrono = "0.4"
hdf5 = "0.8.1"
hdf5-sys = "0.8.1"
ndarray = "0.15.6"
ccsds = { path = "../ccsds-rs/lib" }
crossbeam = "0.8.4"
lazy_static = "1.4.0"
leap-seconds = "0.1.0"
serde = { version = "1.0", features = ["serde_derive"] }
serde_yaml = "0.9"
tempfile = "3.10.1"
tracing = { version = "0.1", features = ["log"] }
thiserror = "1.0.59"
tracing-subscriber = { version = "0.3.18", features = ["fmt", "env-filter"] }
clap = { version = "4.5.7", features = ["derive"] }
