name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - name: Update package index
      run: sudo apt -y update
    - name: Install packages
      run: sudo apt -y install libhdf5-dev curl
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Download Testdata
      run: ./scripts/fetch_testdata.sh
    - name: Build
      run: cargo build
    - name: Run tests
      run: cargo test
